// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    cookieSecret: 'pc_web_zdh',
    db: 'pc_web_zdh',
    url: 'mongodb://localhost/pc_web_zdh'
  };

}).call(this);

//# sourceMappingURL=settings.map
