// Generated by CoffeeScript 1.7.1
(function() {
    var User, mongodb, settings;
    var request = require('request');
    var url = 'http://127.0.0.10:8089/api/worker/printGroupWorkers?'
    User = require('../models/user');
    var qs = require('querystring')
    settings = require('../settings');
    var params =
        { 
            groupId : "1db45816dac94753a342eeb28c23d5dc",
            projectId : "123",
            oderByString: "created_at_in desc"
        }
    var updateParams = {
        jobId: "123",
        orderRank: 1
    }    
    url += qs.stringify(params)

    mongodb = require('mongodb').Db;
    module.exports = function(app) {

        app.get('/', function(req, res) {
            res.render('index', { title: 'aa' });
        });

        app.get('/drop', function(req, res) {
            res.render('drop', { title: 'aa' });
        });

        
        app.get('/drop2', function(req, res) {
            return request.post({url:url}, function (error, response, body) {
              if (!error && response.statusCode == 200) {
                res.render('drop2', { title: 'aa', data: body });
                // res.end(body);
              }else{
                 res.end(JSON.stringify('{"bode":"'+url+'"}'));
              }
            })
        });

        app.get('/request', function(req, res) {
            return request.get({url:url}, function (error, response, body) {
              if (!error && response.statusCode == 200) {
                res.end(body);
              }else{
                 res.end(JSON.stringify('{"bode":"'+url+'"}'));
              }
            })
        });

        app.get('/job/update', function(req, res) {
            return request.post({url:url}, function (error, response, body) {
              if (!error && response.statusCode == 200) {
                res.end(body);
              }else{
                 res.end(JSON.stringify('{"bode":"'+url+'"}'));
              }
            })
        });
        
        app.get('/addPerson', function(req, res) {
            res.render('addPerson', { title: 'Index' });
        });
        
        app.get('/angular', function(req, res) {
            res.render('angular', { title: 'Index' });
        });

        app.get('/api/angular', function(req, res) {
            var data = {
                age: 28     
            }
            res.end(JSON.stringify(data));
        });

        app.get('/print', function(req, res) {
            res.render('print', { title: 'Index' });
        });

        app.get('/printCard', function(req, res) {
            res.render('printCard', { title: 'Index' });
        });

        app.get('/printWorkes', function(req, res) {
            res.render('printWorkes', { title: 'Index' });
        });

		app.post('/api/group/all', function(req, res) {
            var data =  [{"id":"0e56ba29c25b45d2827c741ff4739ebf","text":"新增分组_1","children"
:[]},{"id":"14185d467ab9402aae486c18d4029a13","text":"施工事业部","children":[{"id":"0b27bc49a8744af19a91ab9ed5f6fd09"
,"text":"材料组"},{"id":"1db45816dac94753a342eeb28c23d5dc","text":"模架组"},{"id":"b82d14f1315c4c8383408c9b9cc3238d"
,"text":"钢筋组"},{"id":"f63872e0500a4925bc32080970e555cd","text":"推广部"},{"id":"f79770295b3048278c736d9cfc986921"
,"text":"劳务组"}]},{"id":"d73ae0a8c84a4168a76046e25d11dd70","text":"专业设备项目部","children":[{"id":"a7bbf892d6f94366bc86101af76f1300"
,"text":"专业设备组"}]}]
            res.end(JSON.stringify(data));
        });
    //module.exports    
    };
//(function()    
}).call(this);
